---
title: "Intial_Investigation"
author: "Stryder Coleman"
date: "April 14, 2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Intial Investigation

Libraries
```{r libraries}
library(readxl)
library(tidyverse)
library(caret)
```
Data Imports
```{r import, include=FALSE}
Summary_Basket_2019 <- read_csv("Summary_Basket_2019.csv")
Summary_Basket_2020 <- read_csv("Summary_Basket_2020.csv")
Summary_Basket_2021 <- read_csv("Summary_Basket_2021.csv")
UPC_Hack_Cereal2 <- read_csv("UPC_Hack_Cereal2.csv")
UPC_Hack_Cleaners2 <- read_csv("UPC_Hack_Cleaners2.csv")
Shopper_Tabs1 <- read_excel("Shopper_Tabs_1.xlsx")
Shopper_Tabs2 <- read_excel("Shopping_Tabs_2.xlsx")
Shopper_Tabs3 <- read_excel("Shopper_Tabs_3.xlsx")

```

#functions

```{r barvar}
#Count the amount occurrences of an attribute
#Index: which attribute
#data: the data set
barVar <- function(data, index = 0) {
    library("tidyverse")
    library("ggpubr")
  
    final_plot = NULL
    #index == 0: plot all attribute counts and combine
    if (index == 0) {
      plots <- vector(mode = "list", length = ncol(data))
      #for each attribute
      for(i in 1:ncol(data)) {
        
        #Count occurences
        temp <- data %>%
        count(.[, i]) %>%
          rename("x" = names(.[1]))

        #plot the occurences
        plots[[i]] <- ggplot(temp,aes(y = n, x = x)) +
        geom_bar(stat = "identity", aes(fill = n)) + 
        theme (axis.text.x = element_text (angle = 45, vjust = 1, hjust=1), 
               legend.position="none") + xlab(names(data[i]))
                
      }
      final_plot <- ggarrange(plotlist = plots, labels = c(1:ncol(data)))
      #index > 0: plot a single attribute count(based on index)
    } else if(index > 0) {
      
        
          #count Occurences
          temp <- data %>%
          count(.[, index])  %>%
            rename("x" = names(.[1]))
      
          #plot the occurences
          final_plot <- #ggplot(temp, aes(y = n,x = names(data[index]))) +
          ggplot(temp, aes(y = n,x = reorder(x,n))) +
          geom_bar(stat = "identity", aes(fill = n)) + 
          theme (axis.text.x = element_text (angle = 45, vjust = 1, hjust=1)) +
            xlab(names(data[index]))
    }
    
    final_plot
}
```

```{r countNA}
countNA <- function(data, graph = FALSE) {
  temp <- tibble(Name = names(data), naAmount = 0)
  for (i in 1:nrow(temp)) {
  temp[i, 2] = sum(is.na(data[i]))
  }
  if(graph == TRUE) {
    ggplot(temp,aes(y = naAmount, x = reorder(Name,-naAmount))) +
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text (angle = 45, vjust = 1, hjust=1)) +
      xlab("Attributes")
  } else {
    temp %>%
      arrange(desc(naAmount))
  }
}
```



#Remove empty rows
```{r remove_empty_rows}
remove_empty_rows <- function(.source) {
  empty_rows <- apply(.source, 1, function(.source) all(is.na(.source)))
  cleaned <- .source[!empty_rows,]
  return(cleaned)
}
```

#Clean excel imported data
```{r}
Shopper_Tabs1 <- remove_empty_rows(Shopper_Tabs1)
Shopper_Tabs2 <- remove_empty_rows(Shopper_Tabs2)
Shopper_Tabs3 <- remove_empty_rows(Shopper_Tabs3)
view(Shopper_Tabs1)
view(Shopper_Tabs2)
view(Shopper_Tabs3)
```

#Investigate Summary_Basket_2019
```{r}
  #view(Summary_Basket_2019)
  filter(Summary_Basket_2019,Summary_Basket_2019$Online == 1)
  OnlineVStore_2019 <- Summary_Basket_2019 %>% count(Online)

```

#Investigate Summary_Basket_2020
```{r}
  #view(Summary_Basket_2020)
  filter(Summary_Basket_2020,Summary_Basket_2020$Online == 1)
  OnlineVStore_2020 <- Summary_Basket_2020 %>% count(Online)

```

#Investigate Summary_Basket_2021
```{r}
  #view(Summary_Basket_2021)
  filter(Summary_Basket_2021,Summary_Basket_2021$Online == 1) %>%
  rename()
  OnlineVStore_2021 <- Summary_Basket_2021 %>% count(Online)
  

```


Joining 
```{r}
  
  OvR <- left_join(x = OnlineVStore_2019, y = OnlineVStore_2020, by = "Online")
  OvR <- left_join(x=OvR, y = OnlineVStore_2021, by = "Online")
  
  newnames <- c("Online", "2019", "2020", "2021")  
  oldnames <- c("Online", "n.x", "n.y", "n")
  
  OvR <- OvR %>%
    rename_with(~ newnames, all_of(oldnames))
  OvR

```

