---
title: "product_repition"
author: "Tye Leckinger"
date: "4/16/2022"
output: html_document
---
Libraries
```{r libraries}
library(readxl)
library(tidyverse)
library(caret)
library(dplyr)
library(stringr)
library(knitr)
library(treemap)
library(arules)
library(stats)
#library(gapminder)


```
Data Imports
```{r import, include=FALSE}
Summary_Basket_2019 <- read_csv("Summary_Basket_2019.csv")
Summary_Basket_2020 <- read_csv("Summary_Basket_2020.csv")
Summary_Basket_2021 <- read_csv("Summary_Basket_2021.csv")
UPC_Hack_Cereal2 <- read_csv("UPC_Hack_Cereal2.csv")
UPC_Hack_Cleaners2 <- read_csv("UPC_Hack_Cleaners2.csv")
Shopper_Tabs1 <- read_excel("Shopper_Tabs_1.xlsx")
Shopper_Tabs2 <- read_excel("Shopping_Tabs_2.xlsx")
Shopper_Tabs3 <- read_excel("Shopper_Tabs_3.xlsx")
Cereal_Hackathon_Data_Maps <- read_excel("Hackathon_Data_Maps.xlsx")
Cleaners_Hackathon_Data_Maps <- read_excel("Hackathon_Data_Maps.xlsx", sheet = 2)
#--------------------------------------------------------------
UPC_Hack_Cereal2 <- UPC_Hack_Cereal2 %>% 
      mutate(date = as.Date(str_c("20",date)))
UPC_Hack_Cleaners2 <- UPC_Hack_Cleaners2 %>% 
      mutate(date = as.Date(str_c("20",date)))

```

```{r}
numToMonth<- function(num) {
  factor(c("January", 
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"),
    levels = c("January", 
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"))[num]
}
```




```{r}
cereal_bought <- UPC_Hack_Cereal2 %>%
  rename(UPC = "upc") %>%
  mutate(month = format(date, "%m") %>% 
           as.integer() %>% 
           numToMonth(), 
         year = format(date, "%y")) %>%
  group_by(UPC,month, year) %>%
  summarise(total_amount_bought = sum(qty))  %>%
  left_join(y = .,x = Cereal_Hackathon_Data_Maps, by = "UPC") %>%
  filter(!is.na(total_amount_bought))

cleaners_bought <-  UPC_Hack_Cleaners2 %>%
  rename(UPC = "upc") %>%
  mutate(month = format(date, "%m") %>% 
           as.integer() %>% 
           numToMonth(), 
         year = format(date, "%y")) %>%
  group_by(UPC,month, year) %>%
  summarise(total_amount_bought = sum(qty))  %>%
  left_join(y = .,x = Cleaners_Hackathon_Data_Maps, by = "UPC") %>%
  filter(!is.na(total_amount_bought))

```
```{r}
#cereal_bought %>%
#  ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
#  theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
#  geom_bar(stat = "identity") +
#  facet_wrap(~year) +
#  labs(title = 'Month: {frame_time}', x = 'Brand', y = 'Total Bought') +
#  transition_time(month) +
#  ease_aes('linear')
```


```{r Cereal Brand Popularity per month (2019,2020,2021)}
brand_bought <- cereal_bought %>%
  group_by(Brand,month, year) %>%
  summarise(total_bought_brand = sum(total_amount_bought))
#------------------------------- Year 2019
brand_bought %>% 
  filter(total_bought_brand > 5000) %>%
  filter(year == "19") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity")  + 
  facet_wrap(~month) +
  ggtitle("Year 2019")
#------------------------------- Year 2020
brand_bought %>% 
  filter(total_bought_brand > 5000) %>%
  filter(year == "20") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity") + 
  facet_wrap(~month) +
  ggtitle("Year 2020")
#------------------------------- Year 2021
brand_bought %>% 
  filter(total_bought_brand > 5000) %>%
  filter(year == "21") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity") + 
  facet_wrap(~month) +
  ggtitle("Year 2021")
```


```{r, floating brands}
brand_bought %>%
  group_by(Brand) %>%
  filter(year == "19") %>%
  filter(total_bought_brand > 5000) %>%
  count() %>%
  filter(n < 12)

brand_bought %>%
  group_by(Brand) %>%
  filter(year == "20") %>%
  filter(total_bought_brand > 5000) %>%
  count() %>%
  filter(n < 12)

brand_bought %>%
  group_by(Brand) %>%
  filter(year == "21") %>%
  filter(total_bought_brand > 5000) %>%
  count() %>%
  filter(n < 12)
```

* These are the brands that do not exceed 5000 for all 12 months.  

```{r}
brand_bought <- cleaners_bought %>%
  group_by(Brand,month, year) %>%
  summarise(total_bought_brand = sum(total_amount_bought))
#------------------------------- Year 2019
brand_bought %>% 
  filter(total_bought_brand > 500) %>%
  filter(year == "19") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity")  + 
  facet_wrap(~month) +
  ggtitle("Year 2019")
#------------------------------- Year 2020
brand_bought %>% 
  filter(total_bought_brand > 500) %>%
  filter(year == "20") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity") + 
  facet_wrap(~month) +
  ggtitle("Year 2020")
#------------------------------- Year 2021
brand_bought %>% 
  filter(total_bought_brand > 500) %>%
  filter(year == "21") %>%
ggplot(aes(x = reorder(Brand,total_bought_brand), y = total_bought_brand, fill = Brand)) + 
        theme (axis.text.x = element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom") +
  geom_bar(stat = "identity") + 
  facet_wrap(~month) +
  ggtitle("Year 2021")
```

* strangely Lysol had better sales in 2019, and 2020 but not 2021. 
  > https://fortune.com/2021/07/27/post-pandemic-shopping-ups-lysol-costco/

* Lysol also had a spike in march of 2020. I assume this is because of the 
need for Lysol wipes because of covid.


# Do not run, took 4 hours to compute
```{r transform_set}

tmp <- Cereal_Hackathon_Data_Maps %>%
  rename(Category = "Cat")

UPC_All <- rbind(UPC_Hack_Cereal2, UPC_Hack_Cleaners2)
datamap_all <- rbind(Cleaners_Hackathon_Data_Maps, tmp) %>%
  rename(upc = "UPC")

All_Products <- UPC_All %>% 
  left_join(y = ., x = datamap_all, by = "upc")

tmp <- Cereal_Hackathon_Data_Maps %>%
  rename(Category = "Cat")

UPC_All <- rbind(UPC_Hack_Cereal2, UPC_Hack_Cleaners2)
datamap_all <- rbind(Cleaners_Hackathon_Data_Maps, tmp) %>%
  rename(upc = "UPC")

All_Products <- UPC_All %>% 
  left_join(y = ., x = datamap_all, by = "upc") %>%
  filter(!is.na(HHID))



HHID_List <- unique(All_Products$HHID)
upc_unique <-unique(All_Products$upc)
basket_frame <- data.frame(matrix(0, ncol = length(upc_unique), nrow = length(HHID_List)))
names(basket_frame) = upc_unique



for(k in 1:nrow(All_Products)) {
      basket_frame[which(HHID_List == All_Products$HHID[k]),
                   names(basket_frame) == All_Products$upc[k]] <- 1
}



for(i in 1:length(names(basket_frame))) {
  names(basket_frame)[i] <- (All_Products %>%
                               filter(upc == names(basket_frame)[i]) %>% select(Description))[1,1]
}
  #basket_frame[i,] = 0
```

```{r}
load("basket_frame.Rda")
```

```{r}
load("basket_frame_LABELS.Rda")
basket_frame <- basket_frame[1:length(basket_frame)-1]
basket_frame <- lapply(basket_frame, function(x) as.character(x))
basket_frame <- as_tibble(basket_frame)

#basket_frame <- as.factor(basket_frame)

```


```{r}
transactions <- read.transactions("Hackathon_Data_Maps.xlsx", format = "single", cols = c(1,3))
```


```{r}
rules <- apriori(basket_frame)
```

```{r}
rules <- apriori(basket_frame,parameter = list(minlen=2, maxlen=5,supp=.1, conf=.5))
#quality(rules)<-round(quality(rules),digits=3)
#rules.sorted <- filter(rules, lhs == 0)
```



```{r}


temp_UPC <- UPC_Cereal %>% filter(UPC == 3800000917)
  UPC_Grouped_Daily <- temp_UPC %>%
  group_by(date) %>%
  summarise(sold_per_day = sum(qty)) 
 
  UPC_Grouped_Daily %>%
  ggplot(aes(y = sold_per_day, x = date)) +
  geom_line(color = "lightblue", alpha = .9) +
  geom_smooth(color = "blue") +
  ggtitle(temp_UPC$Description[1])
  
  
fftmodel <- UPC_Grouped_Daily %>%
  ts()

```
```{r}
brand_performance <- UPC_Cereal%>%
  group_by(`Parent Brand`,date) %>%
  summarise(total_products = sum(qty))

brand_performance %>%
ggplot(aes(y = total_products, x = date, color = `Parent Brand`)) +
  geom_point() #+
 # theme(legend.position="none")
  


```


